### PR TITLE
Add more module mappings

### PR DESCRIPTION
**Pull request by fendor**

### CODE REVIEW

**Comment by hsyl20** [comment]
It doesn't build with GHC 8.10:

```
Error:
    Problem with module re-exports:
      - The module 'GHC.Builtin.Names'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.Names.TH'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.PrimOps'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.RebindableNames'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.Types'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.Types.Literals'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.Types.Prim'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.Uniques'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'GHC.Builtin.Utils'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
    In the stanza 'library'
    In the inplace package 'ghc-api-compat-8.6'
```

I have just added a CI so it should be easier to catch now if you update your PR.

**Comment by fendor** [comment]
Oh, I totally forgot that. Need to split the ghc-8.11 part out into its own sub-section

**Comment by fendor** [comment]
Ready for merge?

**Comment by hsyl20** [comment]
@fendor Yes, thanks!

**Pull request merged**
